# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lassoPathDense <- function(X, y, family, standardize, screening_type, path_length, maxit, tol_infeas, tol_gap, gamma, force_kkt_check, line_search, verbosity) {
    .Call(`_LookAheadScreening_lassoPathDense`, X, y, family, standardize, screening_type, path_length, maxit, tol_infeas, tol_gap, gamma, force_kkt_check, line_search, verbosity)
}

lassoPathSparse <- function(X, y, family, standardize, screening_type, path_length, maxit, tol_infeas, tol_gap, gamma, force_kkt_check, line_search, verbosity) {
    .Call(`_LookAheadScreening_lassoPathSparse`, X, y, family, standardize, screening_type, path_length, maxit, tol_infeas, tol_gap, gamma, force_kkt_check, line_search, verbosity)
}

